 <button class="dropdown-item edit-app" data-id="{{ $app->id }}" data-app_name="{{ $app->app_name }}"
     data-desc_app="{{ $app->desc_app }}" data-url_app="{{ $app->url_app }}" data-url_doc="{{ $app->url_doc }}"
     data-url_git="{{ $app->url_git }}" data-env_dev="{{ $app->env_dev }}" data-url_dev="{{ $app->url_dev }}"
     data-adr_serv_dev="{{ $app->adr_serv_dev }}" data-nom_dns="{{ $app->nom_dns }}"
     data-sys_exp_dev="{{ $app->sys_exp_dev }}" data-vers_sys_dev="{{ $app->vers_sys_dev }}"
     data-dist_sys_dev="{{ $app->dist_sys_dev }}" data-adr_serv_bd_dev="{{ $app->adr_serv_bd_dev }}"
     data-sys_exp_bd_dev="{{ $app->sys_exp_bd_dev }}" data-nom_bd_dev="{{ $app->nom_bd_dev }}"
     data-port_bd_dev="{{ $app->port_bd_dev }}" data-user_bd_dev="{{ $app->user_bd_dev }}"
     data-lang_deve_dev="{{ $app->lang_deve_dev }}" data-vers_lang_dev="{{ $app->vers_lang_dev }}"
     data-fram_dev="{{ $app->fram_dev }}" data-vers_fram_dev="{{ $app->vers_fram_dev }}"
     data-critical_dev='@json($app->critical_dev ? json_decode($app->critical_dev) : [])' data-statut_dev="{{ $app->statut_dev }}"
     data-env_prod="{{ $app->env_prod }}" data-url_prod="{{ $app->url_prod }}"
     data-adr_serv_prod="{{ $app->adr_serv_prod }}" data-sys_exp_prod="{{ $app->sys_exp_prod }}"
     data-vers_sys_prod="{{ $app->vers_sys_prod }}" data-dist_sys_prod="{{ $app->dist_sys_prod }}"
     data-adr_serv_bd_prod="{{ $app->adr_serv_bd_prod }}" data-sys_exp_bd_prod="{{ $app->sys_exp_bd_prod }}"
     data-nom_bd_prod="{{ $app->nom_bd_prod }}" data-port_bd_prod="{{ $app->port_bd_prod }}"
     data-user_bd_prod="{{ $app->user_bd_prod }}" data-lang_deve_prod="{{ $app->lang_deve_prod }}"
     data-vers_lang_prod="{{ $app->vers_lang_prod }}" data-fram_prod="{{ $app->fram_prod }}"
     data-vers_fram_prod="{{ $app->vers_fram_prod }}" data-critical_prod='@json($app->critical_prod ? json_decode($app->critical_prod) : [])'
     data-statut_prod="{{ $app->statut_prod }}" data-env_test="{{ $app->env_test }}"
     data-url_test="{{ $app->url_test }}" data-adr_serv_test="{{ $app->adr_serv_test }}"
     data-sys_exp_test="{{ $app->sys_exp_test }}" data-vers_sys_test="{{ $app->vers_sys_test }}"
     data-dist_sys_test="{{ $app->dist_sys_test }}" data-adr_serv_bd_test="{{ $app->adr_serv_bd_test }}"
     data-sys_exp_bd_test="{{ $app->sys_exp_bd_test }}" data-nom_bd_test="{{ $app->nom_bd_test }}"
     data-port_bd_test="{{ $app->port_bd_test }}" data-user_bd_test="{{ $app->user_bd_test }}"
     data-lang_deve_test="{{ $app->lang_deve_test }}" data-vers_lang_test="{{ $app->vers_lang_test }}"
     data-fram_test="{{ $app->fram_test }}" data-vers_fram_test="{{ $app->vers_fram_test }}"
     data-critical_test='@json($app->critical_test ? json_decode($app->critical_test) : [])' data-statut_test="{{ $app->statut_test }}"
     data-bs-toggle="modal" data-bs-target="#editAppModal">
     <i class="bi bi-pencil-fill me-2"></i> Modifier
 </button>
